// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0TfyaRENAyV4OyUOoweQMhZQXJcULjf4',
    appId: '1:348959279770:android:8c97ccfc105df97f6eed23',
    messagingSenderId: '348959279770',
    projectId: 'my-unige-board',
    storageBucket: 'my-unige-board.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQQGXgAgCVHfWP1yPvz45lO-c65DE7rlA',
    appId: '1:348959279770:ios:ac0b002d45787ee56eed23',
    messagingSenderId: '348959279770',
    projectId: 'my-unige-board',
    storageBucket: 'my-unige-board.appspot.com',
    iosBundleId: 'com.example.unigeBoard',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiyPrAYyBvVByAtd-vXjrWXKENkM_cIaM',
    appId: '1:348959279770:web:e578894ba194069b6eed23',
    messagingSenderId: '348959279770',
    projectId: 'my-unige-board',
    authDomain: 'my-unige-board.firebaseapp.com',
    storageBucket: 'my-unige-board.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQQGXgAgCVHfWP1yPvz45lO-c65DE7rlA',
    appId: '1:348959279770:ios:ac0b002d45787ee56eed23',
    messagingSenderId: '348959279770',
    projectId: 'my-unige-board',
    storageBucket: 'my-unige-board.appspot.com',
    iosBundleId: 'com.example.unigeBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiyPrAYyBvVByAtd-vXjrWXKENkM_cIaM',
    appId: '1:348959279770:web:b210dd180a52d38a6eed23',
    messagingSenderId: '348959279770',
    projectId: 'my-unige-board',
    authDomain: 'my-unige-board.firebaseapp.com',
    storageBucket: 'my-unige-board.appspot.com',
  );

}